name = "vkis-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "vkis-school-db"
database_id = "ab2c83e0-e555-480f-aba1-14653c0345de"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "vkis-school-uploads"

[vars]
JWT_SECRET = "schoolsync-secret-key-2026-change-in-production"
DEFAULT_PASSWORD = "School@2026"
# Set DEV_MODE to "true" for local development only; remove or set to "" in production
DEV_MODE = "true"
